### ISSUE TITLE
Backbone retinanet 

### ISSUE THREAD

**Issue by abhigoku10** [best-of-acrv/fcos#2]
@yzuo89  in the config file you have mentioned that backbone is "R-50-FPN-RETINANET" does that mean it includes retinanet for what purpose

**Comment by btalb** [comment]
Please see the [links in the related resources section](https://github.com/best-of-acrv/fcos#related-resources) for the best places to follow up on this question.

The config is fed to Detectron2, so [their documentation](https://detectron2.readthedocs.io/en/latest/index.html) might be the best placed to dig into what's inferred by the backbone assignment.
